---
title: Een afbeelding toevoegen en tekenen
hero_image: images/banner.png
description: Een afbeelding toevoegen en tekenen
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Een afbeelding toevoegen en tekenen
