title: Add and draw an image
hero_image: images/banner.png
description: Add and draw an image
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Add and draw an image
