---
title: Ychwanegu a llunio delwedd
hero_image: images/banner.png
description: Ychwanegu a llunio delwedd
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Ychwanegu a llunio delwedd
