---
title: Adicionar e desenhar uma imagem
hero_image: images/banner.png
description: Adicionar e desenhar uma imagem
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Adicionar e desenhar uma imagem
