---
title: Agrega y dibuja una imagen
hero_image: images/banner.png
description: Agrega y dibuja una imagen
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Agrega y dibuja una imagen
