---
title: Ajouter et dessiner une image
hero_image: images/banner.png
description: Ajouter et dessiner une image
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Ajouter et dessiner une image
