---
title: Carica e disegna un'immagine
hero_image: images/banner.png
description: Carica e disegna un'immagine
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Carica e disegna un'immagine
